// 8x8 픽셀 아이콘 (x = 채움). 액션/음식 키와 동일한 이름으로 조회한다.
export const PIXEL_ICONS: Record<string, string[]> = {
  // --- 액션 ---
  feed: [
    "........",
    "........",
    ".xxxxxx.",
    "xxxxxxxx",
    "xxxxxxxx",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  snack: [
    "........",
    "..xxxx..",
    ".xxx.xx.",
    ".xxxxxx.",
    ".xx.xxx.",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  study: [
    "........",
    ".xxxxxx.",
    ".x.xx.x.",
    ".x.xx.x.",
    ".x.xx.x.",
    ".x.xx.x.",
    ".xxxxxx.",
    "........",
  ],
  exercise: [
    "........",
    "x......x",
    "xx....xx",
    "xxxxxxxx",
    "xxxxxxxx",
    "xx....xx",
    "x......x",
    "........",
  ],
  selfDev: [
    "...xx...",
    "...xx...",
    ".xxxxxx.",
    "xxxxxxxx",
    ".xxxxxx.",
    ".xx..xx.",
    ".x....x.",
    "........",
  ],
  read: [
    "........",
    ".xxxxxx.",
    ".xxxxxx.",
    ".x....x.",
    ".xxxxxx.",
    ".x....x.",
    ".xxxxxx.",
    "........",
  ],
  play: [
    "........",
    "..xxxx..",
    ".xx.xxx.",
    ".xxxx.x.",
    ".x.xxxx.",
    ".xxx.xx.",
    "..xxxx..",
    "........",
  ],
  bath: [
    "...x....",
    "...x....",
    "..xxx...",
    "..xxx...",
    ".xxxxx..",
    ".xx.xx..",
    "..xxx...",
    "........",
  ],
  nap: [
    "........",
    "........",
    ".x....x.",
    ".xxxxxx.",
    "xxxxxxxx",
    "x......x",
    "........",
    "........",
  ],
  sleep: [
    "..xxxx..",
    ".xxxx...",
    ".xx.....",
    ".xx.....",
    ".xx.....",
    ".xxxx...",
    "..xxxx..",
    "........",
  ],

  // --- 운동(세분화) ---
  cardio: [
    "........",
    "...xxx..",
    "..x...x.",
    ".x.....x",
    "x.......",
    "xxxxxxx.",
    "........",
    "........",
  ],
  strength: [
    "........",
    "x......x",
    "xx....xx",
    "xxxxxxxx",
    "xxxxxxxx",
    "xx....xx",
    "x......x",
    "........",
  ],

  // --- 음식 ---
  formula: [
    "..xx....",
    ".xxxx...",
    ".xxxx...",
    "xxxxxx..",
    "xxxxxx..",
    "xxxxxx..",
    "xxxxxx..",
    "........",
  ],
  homeMeal: [
    "........",
    "........",
    ".xxxxxx.",
    "xxxxxxxx",
    "xxxxxxxx",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  cafeteria: [
    "........",
    "xxxxxxxx",
    "x.xx.x.x",
    "x.xx.x.x",
    "xxxxxxxx",
    "........",
    "........",
    "........",
  ],
  convenience: [
    "...x....",
    "..xxx...",
    ".xxxxx..",
    ".xx.xx..",
    "xxxxxxx.",
    "xxxxxxx.",
    "........",
    "........",
  ],
  fastfood: [
    "........",
    ".xxxxxx.",
    "xxxxxxxx",
    ".x.xx.x.",
    ".xxxxxx.",
    "xxxxxxxx",
    ".xxxxxx.",
    "........",
  ],
  salad: [
    "........",
    ".x.xx.x.",
    ".xxxxxx.",
    "xxxxxxxx",
    "xxxxxxxx",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  coffee: [
    "........",
    ".xxxxx.x",
    ".xxxxxxx",
    ".xxxxx.x",
    ".xxxxx..",
    ".xxxxx..",
    "..xxx...",
    "........",
  ],
  ramyeon: [
    ".x.x.x..",
    "........",
    ".xxxxxx.",
    "xxxxxxxx",
    "xxxxxxxx",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  chicken: [
    "...xxx..",
    "..xxxxx.",
    ".xxxxxx.",
    ".xxxxx..",
    "..xxx...",
    "...x....",
    "..xx....",
    ".xx.....",
  ],
  tteokbokki: [
    "........",
    ".xx.xx..",
    "xxxxxxx.",
    ".xx.xx..",
    ".xx.xx..",
    "xxxxxxx.",
    "........",
    "........",
  ],
  samgyeopsal: [
    "........",
    "xxx.xxx.",
    "xxx.xxx.",
    "........",
    "xxx.xxx.",
    "xxx.xxx.",
    "........",
    "xxxxxxxx",
  ],
  chickenBreast: [
    "........",
    "..xxxx..",
    ".xxxxxx.",
    "xx.xx.xx",
    "xxxxxxxx",
    "xx.xx.xx",
    ".xxxxxx.",
    "..xxxx..",
  ],
  fruit: [
    "...x....",
    "..xx....",
    ".xxxxx..",
    "xxxxxxx.",
    "xxxxxxx.",
    "xxxxxxx.",
    ".xxxxx..",
    "..xxx...",
  ],
  boiledEgg: [
    "........",
    "..xxxx..",
    ".xxxxxx.",
    "xxx..xxx",
    "xxx..xxx",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  energyDrink: [
    "..xxxx..",
    ".xxxxxx.",
    ".x....x.",
    ".x.xx.x.",
    ".x.xx.x.",
    ".x....x.",
    ".x....x.",
    ".xxxxxx.",
  ],

  // --- UI ---
  lock: [
    "..xxxx..",
    ".x....x.",
    ".x....x.",
    "xxxxxxxx",
    "xxx..xxx",
    "xxx..xxx",
    "xxxxxxxx",
    "........",
  ],
  check: [
    "........",
    "......x.",
    ".....xx.",
    "x...xx..",
    "xx.xx...",
    ".xxx....",
    "..x.....",
    "........",
  ],
  heart: [
    "........",
    ".xx.xx..",
    "xxxxxxx.",
    "xxxxxxx.",
    ".xxxxx..",
    "..xxx...",
    "...x....",
    "........",
  ],
  praise: [
    "......x.",
    ".xx.xx..",
    "xxxxxxx.",
    "xxxxxxxx",
    ".xxxxx..",
    "..xxx.x.",
    "...x....",
    "........",
  ],
  bolt: [
    "...xx...",
    "..xx....",
    ".xxx....",
    "xxxxxx..",
    "...xxx..",
    "..xx....",
    ".xx.....",
    "........",
  ],
  star: [
    "...xx...",
    "...xx...",
    ".xxxxxx.",
    "xxxxxxxx",
    ".xxxxxx.",
    ".xx..xx.",
    ".x....x.",
    "........",
  ],

  // --- 취업/직무 ---
  briefcase: [
    "..xxxx..",
    "..x..x..",
    "xxxxxxxx",
    "x......x",
    "x..xx..x",
    "x......x",
    "xxxxxxxx",
    "........",
  ],
  resume: [
    ".xxxxxx.",
    ".x....x.",
    ".x.xx.x.",
    ".x....x.",
    ".x.xx.x.",
    ".x....x.",
    ".xxxxxx.",
    "........",
  ],
  folder: [
    "........",
    ".xxx....",
    ".xxxxxx.",
    ".x....x.",
    ".x....x.",
    ".x....x.",
    ".xxxxxx.",
    "........",
  ],
  speech: [
    ".xxxxxx.",
    ".x....x.",
    ".x....x.",
    ".xxxxxx.",
    "..x.....",
    ".x......",
    "........",
    "........",
  ],
  medal: [
    "..xxx...",
    ".x...x..",
    ".x.x.x..",
    ".x...x..",
    "..xxx...",
    "..x.x...",
    ".x...x..",
    "........",
  ],
  chart: [
    "........",
    ".....xx.",
    "..xx.xx.",
    "..xx.xx.",
    ".xxxxxx.",
    ".xxxxxx.",
    "xxxxxxxx",
    "........",
  ],
  code: [
    "........",
    "..x..x..",
    ".x....x.",
    "x......x",
    ".x....x.",
    "..x..x..",
    "........",
    "........",
  ],
  palette: [
    "..xxxx..",
    ".x....x.",
    ".x.x..x.",
    ".x...x.x",
    ".x.x...x",
    ".x....x.",
    "..xxxx..",
    "........",
  ],
  coin: [
    "..xxxx..",
    ".x.xx.x.",
    "x.x..x.x",
    "x.x..x.x",
    "x.x..x.x",
    ".x.xx.x.",
    "..xxxx..",
    "........",
  ],
};
